version: 0.2

env:
  parameter-store:
    REACT_APP_API_URL: "REACT_APP_API_URL"

phases:
  install:
    commands:
      - npm install

  pre_build:
    commands:
      - echo "REACT_APP_API_URL=$REACT_APP_API_URL" > .env.production

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync build/ s3://moviemate-frontend/
      - aws cloudfront create-invalidation --distribution-id E2J8I869OGBEJF --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
